//
//  MoviesListPresenter.swift
//  MoviesApp
//
//  Created by Willian Peres on 09/05/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesListPresentationLogic {
    func presentFirstData(response: MoviesList.InitialFetch.Response) -> Void
    func presentSecondScreen(withColor color: UIColor) -> Void
}

class MoviesListPresenter: MoviesListPresentationLogic {
    weak var viewController: MoviesListDisplayLogic?
    
    func presentFirstData(response: MoviesList.InitialFetch.Response) {
        let movies = response.data.results.map { MovieModel.from($0) }
        let viewModel = MoviesList.InitialFetch.ViewModel(movies: movies)
        viewController?.displayFirstData(viewModel: viewModel)
    }
    
    func presentSecondScreen(withColor color: UIColor) {
        viewController?.displaySecondScreen(withColor: color)
    }
}
