//
//  MoviesListModels.swift
//  MoviesApp
//
//  Created by Willian Peres on 09/05/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MoviesList {
  enum InitialFetch {
    struct Request {}
      
    struct Response {
        let data: MoviesListResponseDTO
    }
      
    struct ViewModel {
        let movies: [MovieModel]
    }
  }
}
