//
//  MoviesListInteractor.swift
//  MoviesApp
//
//  Created by Willian Peres on 09/05/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesListBusinessLogic {
    // func doSomething(request: MoviesList.Something.Request) -> Void
    func onCellTapped(withColor color: UIColor) -> Void
}

protocol MoviesListDataStore {
    //var name: String { get set }
}

class MoviesListInteractor: MoviesListBusinessLogic, MoviesListDataStore {
    var presenter: MoviesListPresentationLogic?
    var worker: MoviesListWorker?
    //var name: String = ""
    
    // MARK: Do something
    
//    func doSomething(request: MoviesList.Something.Request) {
//        worker = MoviesListWorker()
//        worker?.doSomeWork()
//        
//        let response = MoviesList.Something.Response()
//        presenter?.presentSomething(response: response)
//    }
    
    func onCellTapped(withColor color: UIColor) {
        presenter?.presentSecondScreen(withColor: color)
    }
}
