//
//  MoviesListRouter.swift
//  MoviesApp
//
//  Created by Willian Peres on 09/05/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MoviesListRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToSecondScreen(withColor color: UIColor) -> Void
}

protocol MoviesListDataPassing {
  var dataStore: MoviesListDataStore? { get }
}

class MoviesListRouter: NSObject, MoviesListRoutingLogic, MoviesListDataPassing {
  weak var viewController: MoviesListViewController?
  var dataStore: MoviesListDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}
    
    func routeToSecondScreen(withColor color: UIColor) {
        let secondScreen = SecondScreen()
        secondScreen.configureScreen(withColor: color)
        viewController?.navigationController?.pushViewController(secondScreen, animated: true)
    }

  // MARK: Navigation
  
  //func navigateToSomewhere(source: MoviesListViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: MoviesListDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
