//
//  MoviesListWorker.swift
//  MoviesApp
//
//  Created by Willian Peres on 28/11/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MoviesListWorker {
    private let dataProvider: MoviesDataProvider?
    private var completion: ((Result<[MovieModel]?, HTTPRequestError>) -> Void)?
    
    init(dataProvider: MoviesDataProvider = MoviesDataProvider()) {
        self.dataProvider = dataProvider
        self.dataProvider?.delegate = self
    }
    
    func doFetchMovies(language: String, page: Int, completion: @escaping (((Result<[MovieModel]?, HTTPRequestError>) -> Void))) {
        dataProvider?.fetchMovies(language: language, page: page)
        self.completion = completion
    }
}

extension MoviesListWorker: MoviesDataProviderDelegate {
    func success(model: Any) {
        guard let completion = completion else {
            fatalError("MoviesListWorker: Completion not implemented")
        }
        
        completion(.success(model as? [MovieModel]))
    }
    
    func errorData(_ provider: GenericDataProviderDelegate?, error: Error) {
        guard let completion = completion else {
            fatalError("GlobalValuesWorker: Completion not implemented")
        }
        
        switch error.errorCode {
        case 500:
            completion(.failure(.internalServerError))
        case 400:
            completion(.failure(.badRequestError))
        case 404:
            completion(.failure(.notFoundError))
        case 429:
            completion(.failure(.tooManyRequests))
        default:
            completion(.failure(.undefinedError))
        }
    }
}
