//
//  MoviesListModels.swift
//  MoviesApp
//
//  Created by Willian Peres on 28/11/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MoviesList {
    // MARK: Use cases
    
    enum FetchMovies {
        struct Request {}
        
        struct Response {
            struct MovieResponse {
                let posterPath: String?
            }
            
            let movies: [MovieResponse]
        }
        
        struct ViewModel {
            struct MovieViewModel {
                let imageUrl: String?
            }
            
            var movies: [MovieViewModel]
        }
    }
}
