//
//  MoviesListPresenter.swift
//  MoviesApp
//
//  Created by Willian Peres on 28/11/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesListPresentationLogic {
    func presentMovies(isPagination: Bool, response: MoviesList.FetchMovies.Response)
}

class MoviesListPresenter: MoviesListPresentationLogic {
    weak var viewController: MoviesListDisplayLogic?
    
    // MARK: Do something
    
    func presentMovies(isPagination: Bool, response: MoviesList.FetchMovies.Response) {
        let movies = response.movies.map { movie in
            if let posterPath = movie.posterPath {
                return MoviesList.FetchMovies.ViewModel.MovieViewModel(imageUrl: "https://image.tmdb.org/t/p/w185\(posterPath)")
            } else {
                return MoviesList.FetchMovies.ViewModel.MovieViewModel(imageUrl: nil)
            }
        }
        let viewModel = MoviesList.FetchMovies.ViewModel(movies: movies)
        
        if isPagination {
            viewController?.displayPaginationMovies(viewModel: viewModel)
        } else {
            viewController?.displayMovies(viewModel: viewModel)
        }
    }
}
