//
//  MoviesListInteractor.swift
//  MoviesApp
//
//  Created by Willian Peres on 28/11/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesListBusinessLogic {
    var isFetchingMoreMovies: Bool { get }
    
    func doFetchMovies(isPagination: Bool, request: MoviesList.FetchMovies.Request)
}

protocol MoviesListDataStore {
    //var name: String { get set }
}

class MoviesListInteractor: MoviesListBusinessLogic, MoviesListDataStore {
    private var currentPage = 1
    var isFetchingMoreMovies = false
    
    var presenter: MoviesListPresentationLogic?
    var worker: MoviesListWorker?
    //var name: String = ""
    
    init(presenter: MoviesListPresentationLogic = MoviesListPresenter(), worker: MoviesListWorker = MoviesListWorker()) {
        self.presenter = presenter
        self.worker = worker
    }
    
    // MARK: Do something
    
    func doFetchMovies(isPagination: Bool = false, request: MoviesList.FetchMovies.Request) {
        if isPagination {
            isFetchingMoreMovies = true
        } else {
            currentPage = 1
        }
        
        let pageToFetch = isPagination ? currentPage + 1 : currentPage
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
            self.worker?.doFetchMovies(language: "en-US", page: pageToFetch, completion: { result in
                if isPagination {
                    self.isFetchingMoreMovies = false
                }
                
                switch result {
                case .success(let moviesModel):
                    if isPagination { self.currentPage += 1 }
                    
                    self.createMoviesResponse(isPagination: isPagination, movies: moviesModel)
                case .failure(let error):
                    print("Error")
                    print(error)
                }
            })
        }
    }
    
    func createMoviesResponse(isPagination: Bool, movies: [MovieModel]?) {
        if let movies {
            let moviesResponse = movies.map { movie in
                return MoviesList.FetchMovies.Response.MovieResponse(posterPath: movie.posterPath)
            }
            let response = MoviesList.FetchMovies.Response(movies: moviesResponse)
            
            presenter?.presentMovies(isPagination: isPagination, response: response)
        } else {
            // TODO: Handle error
        }
    }
}
