//
//  MoviesListViewController.swift
//  MoviesApp
//
//  Created by Willian Peres on 28/11/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SDWebImage

protocol MoviesListDisplayLogic: AnyObject {
    func displayMovies(viewModel: MoviesList.FetchMovies.ViewModel)
    func displayPaginationMovies(viewModel: MoviesList.FetchMovies.ViewModel)
}

private let reuseIdentifier = "Cell"

class MoviesListViewController: UICollectionViewController {
    private var layout = UICollectionViewFlowLayout()
    
    private var moviesViewModel: MoviesList.FetchMovies.ViewModel?
    
    var interactor: MoviesListBusinessLogic?
    var router: (NSObjectProtocol & MoviesListRoutingLogic & MoviesListDataPassing)?
    
    // MARK: Object lifecycle
    
    public init() {
        super.init(collectionViewLayout: layout)
        setup()
    }
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = MoviesListInteractor()
        let presenter = MoviesListPresenter()
        let router = MoviesListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        configureCollectionVC()
        configureRefreshControl()
        
        doFetchMovies()
    }
    
    func configureCollectionVC() {
        collectionView.register(UICollectionViewCell.self, forCellWithReuseIdentifier: reuseIdentifier)
        
        let numberOfColumns = 3
        let screenPadding: CGFloat = 16.0
        let cellSpacing: CGFloat = 8.0
        
        let contentInset = collectionView.contentInset
        let availableWidth = collectionView.bounds.width - screenPadding * 2 - contentInset.left - contentInset.right
        let totalSpacing = CGFloat(numberOfColumns - 1) * cellSpacing
        let cellWidth = (availableWidth - totalSpacing) / CGFloat(numberOfColumns)
        let cellHeight = cellWidth * 1.4
        
        layout.itemSize = CGSize(width: cellWidth, height: cellHeight)
        layout.minimumInteritemSpacing = cellSpacing
        layout.minimumLineSpacing = cellSpacing
        layout.sectionInset = UIEdgeInsets(top: screenPadding, left: screenPadding, bottom: screenPadding, right: screenPadding)
        
        view.backgroundColor = .systemBackground
        
        navigationController?.navigationBar.prefersLargeTitles = true
        title = "Movies"
    }
    
    func configureRefreshControl() {
        collectionView.refreshControl = UIRefreshControl()
        collectionView.refreshControl?.addTarget(self, action: #selector(handleRefreshControl), for: .valueChanged)
    }
    
    @objc func handleRefreshControl() {
        doFetchMovies()
    }
    
    func doFetchMovies(isPagination: Bool = false) {
        let request = MoviesList.FetchMovies.Request()
        interactor?.doFetchMovies(isPagination: isPagination, request: request)
    }
}

// MARK: UICollectionViewDataSource

extension MoviesListViewController {
    override func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return moviesViewModel?.movies.count ?? 15
    }
    
    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: reuseIdentifier, for: indexPath)
        
        cell.layer.cornerRadius = 8
        cell.clipsToBounds = true
        cell.backgroundColor = .secondarySystemBackground
        
        if let imageUrl = moviesViewModel?.movies[indexPath.item].imageUrl {
            let imageView = UIImageView()
            imageView.contentMode = .scaleToFill
            imageView.translatesAutoresizingMaskIntoConstraints = false
            cell.addSubview(imageView)
            
            imageView.topAnchor.constraint(equalTo: cell.topAnchor).isActive = true
            imageView.bottomAnchor.constraint(equalTo: cell.bottomAnchor).isActive = true
            imageView.leftAnchor.constraint(equalTo: cell.leftAnchor).isActive = true
            imageView.rightAnchor.constraint(equalTo: cell.rightAnchor).isActive = true
            
            imageView.sd_setImage(with: URL(string: imageUrl), placeholderImage: nil)
        }
        
        return cell
    }
    
    override func scrollViewDidScroll(_ scrollView: UIScrollView) {
        let position = scrollView.contentOffset.y
        
        guard !(interactor?.isFetchingMoreMovies ?? false) && moviesViewModel?.movies.count != nil else { return }
        
        if position > (collectionView.contentSize.height - 25 - scrollView.frame.size.height) {
            doFetchMovies(isPagination: true)
        }
    }
}

extension MoviesListViewController: MoviesListDisplayLogic {
    func displayMovies(viewModel: MoviesList.FetchMovies.ViewModel) {
        self.moviesViewModel = viewModel
        DispatchQueue.main.async {
            SDImageCache.shared.clearMemory()
            SDImageCache.shared.clearDisk()
            self.collectionView.reloadData()
            self.collectionView.refreshControl?.endRefreshing()
        }
    }
    
    func displayPaginationMovies(viewModel: MoviesList.FetchMovies.ViewModel) {
        self.moviesViewModel?.movies.append(contentsOf: viewModel.movies)
        
        DispatchQueue.main.async {
            self.collectionView.reloadData()
        }
    }
}
