//
//  ListMoviesInteractor.swift
//  MoviesApp
//
//  Created by Willian Peres on 09/05/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviesBusinessLogic {
    // func doSomething(request: ListMovies.Something.Request) -> Void
    func onCellTapped(withColor color: UIColor) -> Void
}

protocol ListMoviesDataStore {
    //var name: String { get set }
}

class ListMoviesInteractor: ListMoviesBusinessLogic, ListMoviesDataStore {
    var presenter: ListMoviesPresentationLogic?
    var worker: ListMoviesWorker?
    //var name: String = ""
    
    // MARK: Do something
    
//    func doSomething(request: ListMovies.Something.Request) {
//        worker = ListMoviesWorker()
//        worker?.doSomeWork()
//        
//        let response = ListMovies.Something.Response()
//        presenter?.presentSomething(response: response)
//    }
    
    func onCellTapped(withColor color: UIColor) {
        presenter?.presentSecondScreen(withColor: color)
    }
}
