//
//  ListMoviesViewController.swift
//  MoviesApp
//
//  Created by Willian Peres on 09/05/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviesDisplayLogic: AnyObject {
    // func displaySomething(viewModel: ListMovies.Something.ViewModel) -> Void
    func displaySecondScreen(withColor color: UIColor) -> Void
}

class ListMoviesViewController: UIViewController {
    var interactor: ListMoviesBusinessLogic?
    var router: (NSObjectProtocol & ListMoviesRoutingLogic & ListMoviesDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = ListMoviesInteractor()
        let presenter = ListMoviesPresenter()
        let router = ListMoviesRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "Movies"
        navigationController?.navigationBar.prefersLargeTitles = true
        
        self.setupUI()
    }
    
    // MARK: Do something
    
    private var collectionView: UICollectionView?
    
    private func setupUI() {
        self.setupCollectionView()
    }
    
    func setupCollectionView() {
        let layout = UICollectionViewFlowLayout()
        
        collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
        
        guard let collectionView = self.collectionView else {
            return
        }
        
        let numberOfColumns = 3.0
        let cellSpacing = 4.0
        
        let totalSpacing = cellSpacing * (numberOfColumns - 1)
        let cellWidth = ((view.frame.size.width - totalSpacing) / numberOfColumns) - 0.1
        let cellHeight = cellWidth * 1.35
        
        layout.itemSize = CGSize(width: cellWidth, height: cellHeight)
        layout.scrollDirection = .vertical
        layout.minimumLineSpacing = cellSpacing
        layout.minimumInteritemSpacing = cellSpacing
        
        collectionView.register(ListMoviesItemCVC.self, forCellWithReuseIdentifier: ListMoviesItemCVC.identifier)
        collectionView.dataSource = self
        collectionView.delegate = self
        collectionView.frame = view.bounds
        
        view.addSubview(collectionView)
    }
    
    //    func doSomething() {
    //        let request = ListMovies.Something.Request()
    //        interactor?.doSomething(request: request)
    //    }
}

extension ListMoviesViewController: ListMoviesDisplayLogic {
    //    func displaySomething(viewModel: ListMovies.Something.ViewModel) {
    //        //nameTextField.text = viewModel.name
    //    }
    
    func displaySecondScreen(withColor color: UIColor) {
        router?.routeToSecondScreen(withColor: color)
    }
}

// Handle logic for the collectionView
extension ListMoviesViewController: UICollectionViewDelegate, UICollectionViewDataSource {
    // Number of items in the collection view
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 30
    }
    
    // Manage the cell at index
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: ListMoviesItemCVC.identifier, for: indexPath) as? ListMoviesItemCVC else {
            fatalError("Failed to dequeue a MovieCell.")
        }
        
        cell.configureCell(color: .random())
        cell.delegate = self
        
        return cell
    }
}

extension ListMoviesViewController: ListMoviesItemCVCDelegate {
    func onCellTapped(color: UIColor) {
        interactor?.onCellTapped(withColor: color)
    }
}
